const assert = require('assert');
const G = require('../app/src/main/assets/core.js');
assert.strictEqual(G.creatures.length,100);
assert.deepStrictEqual(G.defaultState().unlocked,[1]);
assert.strictEqual(G.fishingInputOutcome('idle'),'cast');
assert.strictEqual(G.fishingInputOutcome('waiting'),'retract');
assert.strictEqual(G.fishingInputOutcome('early'),'early-miss');
assert.strictEqual(G.fishingInputOutcome('strike'),'catch');
assert.strictEqual(G.fishingInputOutcome('late'),'late-miss');
assert.strictEqual(G.creatures[0].rarity,'commune');
assert.strictEqual(G.creatures[99].rarity,'mythique');
assert.strictEqual(G.creatures[99].gate,10);
const counts=G.creatures.reduce((a,c)=>{a[c.rarity]=(a[c.rarity]||0)+1;return a},{});
assert.deepStrictEqual(counts,{commune:40,inhabituelle:25,rare:18,epique:10,legendaire:6,mythique:1});
assert.deepStrictEqual(G.thresholds,[0,40,120,260,480,800,1250,1850,2700,3800]);
[[0,1],[39,1],[40,2],[120,3],[260,4],[480,5],[800,6],[1250,7],[1850,8],[2700,9],[3800,10]].forEach(([sold,rank])=>assert.strictEqual(G.rankForSold(sold),rank));
let s=G.defaultState();
assert.strictEqual(G.eligibleLocked(s).length,5);
assert.strictEqual(G.gachaCost(s),450);
for(let i=0;i<5;i++){const c=G.rollCatch(s,()=>0);G.addCatch(s,c)}
assert.strictEqual(G.inventoryCount(s),5);
let sale=G.sellAll(s);
assert.strictEqual(sale.count,5);
assert(s.coins>0);
assert.strictEqual(s.totalSold,5);
let old=G.normalizeState({version:1,unlocked:[1,2,3]});
assert.deepStrictEqual(old.unlocked,[1,2,3]);
const order=['commune','inhabituelle','rare','epique','legendaire','mythique'];
const midpoint=r=>(r[0]+r[1])/2;
for(let i=1;i<order.length;i++)assert(midpoint(G.rarities[order[i]].hit)<midpoint(G.rarities[order[i-1]].hit));
for(const r of order){
  const c=G.creatures.find(x=>x.rarity===r),lo=G.fishingTiming(c,()=>0),hi=G.fishingTiming(c,()=>.999999);
  assert(lo.waitMs>=1800&&hi.waitMs<=5200);
  assert(lo.strikeMs<hi.strikeMs);
  assert(lo.earlyMs<hi.earlyMs);
}
s=G.defaultState();s.coins=99999;
const before=s.unlocked.length,p1=G.pullGacha(s,()=>0);
assert(p1.ok);assert.strictEqual(s.unlocked.length,before+1);
const p2=G.pullGacha(s,()=>0);
assert(p2.ok);assert.notStrictEqual(p1.creature.id,p2.creature.id);
s.streak=3;G.registerMiss(s,'retracted');assert.strictEqual(s.streak,3);assert.strictEqual(s.retractedCasts,1);
G.registerMiss(s,'early');assert.strictEqual(s.streak,0);assert.strictEqual(s.failedHooks,1);
console.log('OK - v1.1 gameplay tests passed');
