const assert = require('assert');
const G = require('../app/src/main/assets/core.js');
assert.strictEqual(G.creatures.length,100);
assert.deepStrictEqual(G.defaultState().unlocked,[1]);
assert.strictEqual(G.defaultState().version,4);
assert.strictEqual(G.fishingInputOutcome('idle'),'cast');
assert.strictEqual(G.fishingInputOutcome('waiting'),'retract');
assert.strictEqual(G.fishingInputOutcome('early'),'early-miss');
assert.strictEqual(G.fishingInputOutcome('strike'),'catch');
assert.strictEqual(G.fishingInputOutcome('late'),'late-miss');
assert.strictEqual(G.fishingInputOutcome('cooldown'),'ignore');
assert.strictEqual(G.postCatchLockMs,3000);
assert.strictEqual(G.creatures[0].rarity,'commune');
assert.strictEqual(G.creatures[99].rarity,'mythique');
assert.strictEqual(G.creatures[99].gate,10);
const counts=G.creatures.reduce((a,c)=>{a[c.rarity]=(a[c.rarity]||0)+1;return a},{});
assert.deepStrictEqual(counts,{commune:40,inhabituelle:25,rare:18,epique:10,legendaire:6,mythique:1});
for(let i=1;i<G.creatures.length;i++)assert(G.creatures[i].value>G.creatures[i-1].value);
assert.strictEqual(G.creatures[0].value,19);
assert(!('weightMinG' in G.creatures[0])&&!('weightMaxG' in G.creatures[0]));
assert.deepStrictEqual(G.thresholds,[0,40,120,260,480,800,1250,1850,2700,3800]);
[[0,1],[39,1],[40,2],[120,3],[260,4],[480,5],[800,6],[1250,7],[1850,8],[2700,9],[3800,10]].forEach(([sold,rank])=>assert.strictEqual(G.rankForSold(sold),rank));
let s=G.defaultState();
assert.strictEqual(G.eligibleLocked(s).length,5);
assert.strictEqual(G.gachaCost(s),450);
const starter=G.creatures[0],minWeight=G.rollWeight(starter,s,()=>0),nearMaxWeight=G.rollWeight(starter,s,()=>.999999);
assert(minWeight<nearMaxWeight);
assert.strictEqual(G.catchValue(starter,minWeight),starter.value);
assert(G.catchValue(starter,nearMaxWeight)>starter.value);
for(let i=0;i<5;i++){const c=G.rollCatch(s,()=>0),w=G.rollWeight(c,s,()=>.25);G.addCatch(s,c,w)}
assert.strictEqual(G.inventoryCount(s),5);
assert.strictEqual(s.coins,G.comboBonus(2)+G.comboBonus(3)+G.comboBonus(4)+G.comboBonus(5));
let sale=G.sellAll(s);
assert.strictEqual(sale.count,5);
assert(s.coins>sale.value);
assert.strictEqual(s.totalSold,5);
let old=G.normalizeState({version:3,unlocked:[1,2,3],coins:123,inventory:{1:2,2:1}});
assert.deepStrictEqual(old.unlocked,[1,2,3]);
assert.strictEqual(old.coins,123);
assert.strictEqual(old.version,4);
assert(Array.isArray(old.inventory)&&old.inventory.length===3);
assert.strictEqual(G.catchValue(G.creatures[0],old.inventory[0].weightG),G.creatures[0].value);
const order=['commune','inhabituelle','rare','epique','legendaire','mythique'];
const midpoint=r=>(r[0]+r[1])/2;
const span=r=>r[1]-r[0];
for(let i=1;i<order.length;i++)assert(midpoint(G.rarities[order[i]].hit)<midpoint(G.rarities[order[i-1]].hit));
for(let i=1;i<order.length;i++)assert(span(G.rarities[order[i]].wait)>span(G.rarities[order[i-1]].wait));
for(let i=1;i<order.length;i++)assert(span(G.rarities[order[i]].early)>span(G.rarities[order[i-1]].early));
assert.deepStrictEqual(G.rarities.commune.early,[450,950]);
assert.deepStrictEqual(G.rarities.inhabituelle.early,[380,1020]);
assert.deepStrictEqual(G.rarities.rare.early,[310,1120]);
assert.deepStrictEqual(G.rarities.epique.early,[250,1240]);
assert.deepStrictEqual(G.rarities.legendaire.early,[190,1380]);
assert.deepStrictEqual(G.rarities.mythique.early,[140,1500]);
assert.deepStrictEqual(G.rarities.mythique.hit,[320,500]);
assert(span(G.rarities.commune.hit)>400);
for(const r of order){
  const c=G.creatures.find(x=>x.rarity===r),lo=G.fishingTiming(c,G.defaultState(),()=>0),hi=G.fishingTiming(c,G.defaultState(),()=>.999999);
  assert.strictEqual(lo.waitMs,G.rarities[r].wait[0]);
  assert.strictEqual(hi.waitMs,G.rarities[r].wait[1]);
  assert(lo.strikeMs<hi.strikeMs);
  assert(lo.earlyMs<hi.earlyMs);
}
let upgraded=G.defaultState();upgraded.upgrades.bait=5;upgraded.upgrades.reel=5;
let baseTiming=G.fishingTiming(starter,G.defaultState(),()=>.5),boostTiming=G.fishingTiming(starter,upgraded,()=>.5);
assert(boostTiming.waitMs<baseTiming.waitMs);
assert(boostTiming.strikeMs>baseTiming.strikeMs);
let heavy=G.defaultState();heavy.upgrades.keeper=5;
assert(G.rollWeight(starter,heavy,()=>.5)>G.rollWeight(starter,G.defaultState(),()=>.5));
assert.strictEqual(G.comboBonus(1),0);
assert.strictEqual(G.comboBonus(2),1);
assert.strictEqual(G.comboBonus(10),5);
assert.strictEqual(G.comboBonus(25),22);
assert.strictEqual(G.comboBonus(50),75);
assert.strictEqual(G.comboBonus(51),75);
assert.strictEqual(G.comboBonus(500),75);
s=G.defaultState();
let w1=G.rollWeight(starter,s,()=>.2),w2=G.rollWeight(starter,s,()=>.8);
let r1=G.addCatch(s,starter,w1),r2=G.addCatch(s,starter,w2);
assert.deepStrictEqual({combo:r1.combo,bonus:r1.bonus},{combo:1,bonus:0});
assert.deepStrictEqual({combo:r2.combo,bonus:r2.bonus},{combo:2,bonus:1});
assert.strictEqual(s.coins,1);
assert.strictEqual(s.comboEarned,1);
assert.strictEqual(s.bestWeightById[starter.id],Math.max(w1,w2));
assert.strictEqual(r2.record,w2>w1);
let marketState=G.normalizeState(JSON.parse(JSON.stringify(s)));
marketState.upgrades.broker=5;
assert(G.inventoryValue(marketState)>G.inventoryValue(s));
let shop=G.defaultState();shop.coins=9999;
assert.strictEqual(G.upgradeStatus(shop,'bait').rankLocked,false);
assert.strictEqual(G.buyUpgrade(shop,'bait').ok,true);
assert.strictEqual(shop.upgrades.bait,1);
assert.strictEqual(G.upgradeStatus(shop,'reel').rankLocked,true);
shop.totalSold=40;
assert.strictEqual(G.upgradeStatus(shop,'reel').rankLocked,false);
for(let i=1;i<order.length;i++){
  const a=G.rarities[order[i-1]].haptic,b=G.rarities[order[i]].haptic;
  assert(midpoint(b)>midpoint(a));
  assert(b[0]<=a[1]);
}
s=G.defaultState();s.coins=99999;
const before=s.unlocked.length,p1=G.pullGacha(s,()=>0);
assert(p1.ok);assert.strictEqual(s.unlocked.length,before+1);
const p2=G.pullGacha(s,()=>0);
assert(p2.ok);assert.notStrictEqual(p1.creature.id,p2.creature.id);
s.streak=3;const heldCoins=s.coins;G.registerMiss(s,'retracted');assert.strictEqual(s.streak,3);assert.strictEqual(s.retractedCasts,1);assert.strictEqual(s.coins,heldCoins);
G.registerMiss(s,'early');assert.strictEqual(s.streak,0);assert.strictEqual(s.failedHooks,1);assert.strictEqual(s.coins,heldCoins);
console.log('OK - v1.2.1 gameplay tests passed');
